{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-retention",
    "version": "30.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.2.2.jar",
          "url": "android-test-plugin-host-retention-30.2.2.jar",
          "size": 44724,
          "sha512": "c43a1f0a3673322eaa7751c24572f54a658417725bd1586c989badc272905b8ad1fe10406652ac3537299d5c8f22020693cb202c75d629fd7f427f83a255a39c",
          "sha256": "0cdc180ccab9c3f29c5b5ab7bcb20647a689b6d59ceea32f7446b2d4e0ed8950",
          "sha1": "448ce769614bc7daf300ed727ad1acd020b9e225",
          "md5": "26056eb1598b039f34accf711ee6500e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-retention-proto",
          "version": {
            "requires": "30.2.2"
          }
        },
        {
          "group": "com.android.tools.emulator",
          "module": "proto",
          "version": {
            "requires": "30.2.2"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.8-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.2.2.jar",
          "url": "android-test-plugin-host-retention-30.2.2.jar",
          "size": 44724,
          "sha512": "c43a1f0a3673322eaa7751c24572f54a658417725bd1586c989badc272905b8ad1fe10406652ac3537299d5c8f22020693cb202c75d629fd7f427f83a255a39c",
          "sha256": "0cdc180ccab9c3f29c5b5ab7bcb20647a689b6d59ceea32f7446b2d4e0ed8950",
          "sha1": "448ce769614bc7daf300ed727ad1acd020b9e225",
          "md5": "26056eb1598b039f34accf711ee6500e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.2.2-javadoc.jar",
          "url": "android-test-plugin-host-retention-30.2.2-javadoc.jar",
          "size": 261,
          "sha512": "0105f93b9e3444a6310e1bdfa689b5cac55b06d620f728fe46f16d0ab1141f547fa0c59df399606ac0fe2efeac692d3b8bdb72132b08b1990ddd25796fde1d8d",
          "sha256": "cd084c5158807a95f889afbb23fc6b108411f05f6c7143c678fad96f89da80c4",
          "sha1": "63e060be83c431cff860806ba0420ca3e21fae63",
          "md5": "305a189fa220c336d2ed53b157f04a7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.2.2-sources.jar",
          "url": "android-test-plugin-host-retention-30.2.2-sources.jar",
          "size": 12718,
          "sha512": "1d1b120cefcea19bb1473b3aa814a21530473217ad026edb1ddd42c51c07f2ace5d5536581ad2bb3573d0f5be156bc6f24f23c04ecf8a603ace72454f23d57f5",
          "sha256": "6947538a2cd556c71c006535721c999b9c9104ab803e5f6716da43409b90c09a",
          "sha1": "ade609e12d007c5c429457851a014b2f5875668b",
          "md5": "3270e1d7006e75a0c04f4f0bed80dc20"
        }
      ]
    }
  ]
}
